tap "atlassian/tap"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "petere/postgresql"
tap "thoughtbot/formulae"
tap "wagoodman/dive"
tap "wercker/wercker"
brew "autoconf"
brew "autojump"
brew "automake"
brew "coreutils"
brew "docker-compose"
brew "exa"
brew "git"
brew "git-crypt"
brew "hstr"
brew "htop"
brew "httpie"
brew "hyper"
brew "jq"
brew "libksba"
brew "libtool"
brew "mas"
brew "openssl@1.1"
brew "pkg-config"
brew "postgresql"
brew "redis"
brew "ripgrep"
brew "terraform"
brew "wget"
brew "yarn"
brew "heroku/brew/heroku"
brew "wagoodman/dive/dive"
cask "1password"
cask "adobe-acrobat-reader"
cask "alfred"
cask "appcleaner"
cask "bartender"
cask "battle-net"
cask "chromedriver"
cask "cyberduck"
cask "dash"
cask "docker"
cask "dropbox"
cask "evernote"
cask "firefox"
cask "google-chrome"
cask "google-cloud-sdk"
cask "gpg-suite"
cask "java"
cask "jetbrains-toolbox"
cask "kindle"
cask "minecraft"
cask "ngrok"
cask "origin"
cask "osirix-quicklook"
cask "qnapi"
cask "quitter"
cask "rocket"
cask "signal"
cask "slack"
cask "spectacle"
cask "steam"
cask "sublime-text"
cask "transmission"
cask "tunnelblick"
cask "tuntap"
cask "vlc"
mas "Day One", id: 1055511498
mas "Horo", id: 1437226581
mas "hr", id: 976253191
mas "iA Writer", id: 775737590
mas "Keynote", id: 409183694
mas "Lungo", id: 1263070803
mas "Magnet", id: 441258766
mas "MindNode", id: 992076693
mas "NordVPN IKE", id: 1116599239
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pixelmator", id: 407963104
mas "Sip", id: 507257563
mas "Things3", id: 904280696
mas "TweetDeck", id: 485812721
